{% set name = "pytablewriter" %}
{% set version = "1.2.0" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 0204a4bb684a22140d640f2599f09e137bcdc18b3dd49426f4a555016e246b46

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python >=3.7
    - setuptools
    - wheel
    - pip
  run:
    - python >=3.7
    - setuptools >=38.3.0
    - dataproperty >=1.0.1,<2
    - mbstrdecoder >=1.0.0,<2
    - pathvalidate >=2.3.0,<4
    - tabledata >=1.3.1,<2
    - tcolorpy >=0.0.5,<1
    - typepy >=1.3.2,<2

test:
  imports:
    - pytablewriter
    - pytablewriter._logger
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/thombashi/pytablewriter
  summary: |
    pytablewriter is a Python library to write a table in various
    formats: CSV / Elasticsearch / HTML / JavaScript / JSON / LaTeX
    / LDJSON / LTSV / Markdown / MediaWiki / NumPy / Excel / Pandas
    / Python / reStructuredText / SQLite / TOML / TSV / YAML.
  dev_url: https://github.com/thombashi/pytablewriter
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - basnijholt
    - ocefpaf
