{% set name = "pytablewriter" %}
{% set version = "0.64.1" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 2954d0dd2ac2dd74eaf4a41301017cb7cbc56962d7751a5d78ae4a4127417eb8

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.6
    - setuptools >=38.3.0
  run:
    - dataproperty >=0.49.1
    - mbstrdecoder >=1.0.0
    - msgfy >=0.1.0
    - pathvalidate >=2.3.0
    - python >=3.6
    - setuptools >=38.3.0
    - tabledata >=1.1.1
    - tcolorpy >=0.0.5
    - typepy >=1.1.1

test:
  imports:
    - pytablewriter
    - pytablewriter._logger
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/thombashi/pytablewriter
  summary: |
    pytablewriter is a Python library to write a table in various
    formats: CSV / Elasticsearch / HTML / JavaScript / JSON / LaTeX
    / LDJSON / LTSV / Markdown / MediaWiki / NumPy / Excel / Pandas
    / Python / reStructuredText / SQLite / TOML / TSV / YAML.
  dev_url: https://github.com/thombashi/pytablewriter
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - basnijholt
